apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: nodeapp
